# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "iac2" do |iac2|
    iac2.vm.box = "ubuntu/focal64"
    iac2.vm.hostname = "iac2-station"
    iac2.vm.network :private_network, ip: "10.0.0.100"
    iac2.vm.provider "virtualbox" do |v|
      v.name = "iac2"    
      v.cpus = 2
      v.memory = 2048
    end
  end

  config.vm.define "server2" do |server2|
    server2.vm.box = "ubuntu/focal64"
    server2.vm.hostname = "server2"
    server2.vm.network :private_network, ip: "10.0.0.110"
    server2.vm.provider "virtualbox" do |v|
      v.name = "server2"    
      v.cpus = 2
      v.memory = 2048
    end
  end
end